# Generated by Django 5.1.3 on 2025-02-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'credit_card'), ('phone_pay', 'phone_pay'), ('paytm', 'paytm'), ('bank_transfer', 'bank_transfer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='pending', max_length=10),
        ),
    ]
